### ISSUE TITLE
Builtins prototype function inadequate.

### ISSUE THREAD

**Issue by Vicest** [Bortize/42_minishell#2]
The builtins function prototype doesn't need to know the full cmd list asked for execution.
It should resemble the execve prototype: e.g: `builtins(char** argv, char** envp)`

Since it just modifies the shell status, it's ok/preffered to have envp as our t_list stucture.
Feel free to add an `int argn` if you want.

**Comment by Bortize** [comment]
Ok. I'll go over it.

**Comment by Bortize** [comment]
It's done (in a commented way for the moment, because I don't know if I'll need it later) 

👉 [builtins.c](https://github.com/Bortize/42_minishell/blob/builtins/srcs/builtins/builtins.c) 👈
