### ISSUE TITLE
Minishell exits unexpectedly

### ISSUE THREAD

**Issue by Vicest** [Bortize/42_minishell#4]
The following arguments make minishell to exit instead of start execution. (as it should)

`>file1`
`<file1`
`>>file1`

**Comment by Vicest** [comment]
Possibly realted to the wait_input function, perhaps part of the parser.

**Comment by Bortize** [comment]
Ok. I'll go over it

**Comment by Bortize** [comment]
I'm not sure, I'm looking into it
I think that the problem of redirections is caused because the type is not assigned at any time. The only place where it was checked was in the "print_cmd" function in the "parse_line" function and it was commented out.

**Comment by Vicest** [comment]
Closed.
Parser no longer comlains about empty arguments.
