### ISSUE TITLE
Need a function to build our env_lst without segafulting when env is NULL.

### ISSUE THREAD

**Issue by Bortize** [Bortize/42_minishell#6]
When I pass it a variable that does not exist in the function `check_existence_environment()` it returns a seg.fault when clearly I want it to reach the end of the List and return a value of `1`.

It is as if it didn't find the `NULL` at the end of the list and it overrides the brakes. I have checked the function `asign_env_struct()` and apparently it is correct.

**Comment by Bortize** [comment]
✅ I have come up with a workaround by adding a counter to the maximum size of the list in the 👉[*ft_lst_find()](https://github.com/Bortize/42_minishell/blob/builtins/srcs/utils.c)👈function. 

❗I know it's not the best way to do it but it works. I will have to keep an eye on it because I have modified a utils function. Therefore, the function becomes an own function of the minishell program and it stops having the category of "utils".

**Comment by Vicest** [comment]
I'm taking a look. I don't quite understand the builtins_env fction. I assume, given the context, that it builds our env_lst out opf the program's envp. If that's the case, just remember that the builting `env` isn't that thing. I'd change the name just to reflect that.

I assigned myself as well to have a function to build the env_lst and renamed the issue to have a more fitting name.

**Comment by Vicest** [comment]
I'll work on your builtin_env, I think it's almost done.

**Comment by Vicest** [comment]
Just as a side note. A list (env_lst) *can* be NULL, it's just an empty lst.

**Comment by Vicest** [comment]
Everything seems to be working fine. Closing it for now.
